### ISSUE TITLE
Checklist before finalizing code

### ISSUE THREAD

**Issue by blahosyl** [blahosyl/dinner-party#11]
- [x] ~~Make sure each `input` content has `\n` at the end~~ checked with mentor, not needed anymore
- [x] re-generate `requirements.txt` file:  Terminal: `pip3 freeze > requirements.txt`
- [x] also make sure requirements don't contain packages that are not in the final version
- [x] unify `""` vs `''` (can be either as long as it's unified, slight pereference for `''` for readability and faster typing)
- [x] delete superfluous commented-out code
- [x] make sure all functions have well-written docstrings
- [x] check/update code comment coverage
- [x] delete unused branches
